const ANNIVERSARY_DAYS = [
{'d': 1, 'm': 1, 'i': 'Năm mới'},
{'d': 4, 'm': 1, 'i': 'Ngày Chữ nổi Thế giới'},
{'d': 24, 'm': 1, 'i': 'Ngày Quốc tế Giáo dục'},
{'d': 27, 'm': 1, 'i': 'Ngày Quốc tế Kỷ niệm Tưởng nhớ Nạn nhân của Nạn diệt chủng Đức quốc xã'},
{'d': 4, 'm': 2, 'i': 'Ngày ung thư thế giới'},
{'d': 6, 'm': 2, 'i': 'Ngày Quốc tế về Không Khoan dung về Gây tổn thương Sinh dục nữ'},
{'d': 12, 'm': 2, 'i': 'Ngày Quốc tế chống sử dụng Binh sĩ Trẻ em'},
{'d': 13, 'm': 2, 'i': 'Ngày Phát thanh Thế giớiNgày Quốc tế Bao cao su'},
{'d': 14, 'm': 2, 'i': 'Ngày Valentine'},
{'d': 20, 'm': 2, 'i': 'Ngày Công lý xã hội thế giới'},
{'d': 21, 'm': 2, 'i': 'Ngày tiếng mẹ đẻ Quốc tế'},
{'d': 1, 'm': 3, 'i': 'Ngày Không phân biệt đối xử'},
{'d': 3, 'm': 3, 'i': 'Ngày Sinh giới Hoang dã Thế giới'},
{'d': 8, 'm': 3, 'i': 'Ngày Quốc tế Phụ nữ'},
{'d': 20, 'm': 3, 'i': 'Ngày Quốc tế Hạnh phúc'},
{'d': 21, 'm': 3, 'i': ['Ngày Quốc tế xóa bỏ Kỳ thị chủng tộc', 'Ngày Thơ Thế giới', 'Ngày Quốc tế Nowruz', 'Ngày Hội chứng Down thế giới', 'Ngày Quốc tế về Rừng']},
{'d': 22, 'm': 3, 'i': 'Ngày Nước Thế giới'},
{'d': 23, 'm': 3, 'i': 'Ngày Khí tượng Thế giới'},
{'d': 24, 'm': 3, 'i': ['Ngày Thế giới phòng chống lao', 'Ngày Quốc tế về Quyền được Sự thật liên quan đến Vi phạm Nhân quyền thô bạo và cho phẩm giá của nạn nhân']},
{'d': 25, 'm': 3, 'i': ['Ngày Quốc tế Tưởng niệm Nạn nhân của chế độ nô lệ và buôn bán nô lê Đại Tây Dương', 'Ngày Quốc tế Đoàn kết với Nhân viên bị giam giữ và Thành viên mất tích']},
{'d': 2, 'm': 4, 'i': 'Ngày Thế giới Nhận thức Tự kỷ'},
{'d': 4, 'm': 4, 'i': 'Ngày Quốc tế Nhận thức Bom mìn và Hỗ trợ hành động Bom mìn'},
{'d': 6, 'm': 4, 'i': 'Ngày Quốc tế Thể thao vì Phát triển và Hòa bình'},
{'d': 7, 'm': 4, 'i': ['Ngày Quốc tế Phản ánh về Diệt chủng ở Rwanda', 'Ngày Sức khỏe Thế giới']},
{'d': 12, 'm': 4, 'i': 'Ngày Quốc tế con người bay vào vũ trụ'},
{'d': 22, 'm': 4, 'i': ['Ngày Quốc tế Mẹ Trái Đất', 'Ngày Pháp Luật Thế giới']},
{'d': 23, 'm': 4, 'i': ['Ngày Sách và Bản quyền Thế giới', 'Ngày tiếng Anh']},
// {'d': 24-30/4	Tuần lễ Tiêm chủng Thế giới'},
// {'d': 25/4	Ngày Sốt rét Thế giới'},
// {'d': 26/4	Ngày Sở hữu trí tuệ thế giới'},
// {'d': 28/4	Ngày Thế giới về an toàn và sức khỏe tại nơi làm việc'},
// {'d': 29/4	Ngày Tưởng niệm tất cả nạn nhân của Chiến tranh hoá học'},
// {'d': 30/4	Ngày Jazz Quốc tế'},
// {'d': 1/5	Ngày Quốc tế Lao động'},
// {'d': 3/5	Ngày Tự do Báo chí thế giới'},
// {'d': Chủ nhật thứ hai của tháng 5	Ngày của Mẹ'},
// {'d': 7/5	Ngày Quốc tế Tình Yêu'},
// {'d': 8/5	Ngày Chữ Thập Đỏ Quốc tế'},
// {'d': 8-9/5	Thời gian cho Tưởng niệm và Hòa giải cho những người thiệt mạng trong Chiến tranh thế giới thứ hai'},
// {'d': 9-10/5	Ngày Chim Di cư thế giới'},
// {'d': 15/5	Ngày quốc tế Gia đình'},
// {'d': Ngày Rằm	Lễ Phật Đản'},
// {'d': 17/5	Ngày Quốc tế chống kỳ thị, phân biệt đối xử với người đồng tính, song tính và chuyển giới (LGBT)'},
// {'d': 	Ngày Hiệp hội Thông tin Thế giới'},
// {'d': 21/5	Ngày Thế giới về Đa dạng Văn hoá vì Đối thoại và Phát triển'},
// {'d': 22/5	Ngày quốc tế Đa dạng sinh học'},
// {'d': 23/5	Ngày Quốc tế Kết thúc Lỗ rò sản khoa'},
// {'d': 29/5	Ngày Quốc tế Gìn giữ Hòa bình Liên Hợp Quốc'},
// {'d': 31/5	Ngày Thế giới không thuốc lá'},
// {'d': 1/6	Ngày Quốc tế Thiếu nhi'},
// {'d': 	Ngày Phụ huynh Toàn cầu'},
// {'d': 4/6	Ngày Quốc tế của Trẻ em vô tội và là Nạn nhân bị xâm lược'},
// {'d': 5/6	Ngày Môi trường Thế giới'},
// {'d': 6/6	Ngày tiếng Nga tại Liên Hợp Quốc'},
// {'d': 8/6	Ngày Đại dương Thế giới'},
// {'d': 12/6	Ngày Thế giới chống Lao động Trẻ em'},
// {'d': 14/6	Ngày Hiến Máu Thế giới'},
// {'d': 15/6	Ngày Thế giới Phòng chống lạm dụng Người cao tuổi'},
// {'d': Chủ nhật thứ ba của tháng 6	Ngày của Cha'},
// {'d': 17/6	Ngày Thế giới chống Sa mạc hóa và Hạn hán'},
// {'d': 20/6	Ngày Tị nạn Thế giới'},
// {'d': 21/6	Ngày Quốc tế Yoga'},
// {'d': 23/6	Ngày Dịch vụ Công cộng Liên Hợp Quốc'},
// {'d': 	Ngày Quốc tế Phụ nữ góa'},
// {'d': 25/6	Ngày Thủy thủ'},
// {'d': 26/6	Ngày Quốc tế chống lạm dụng và buôn bán trái phép ma túy'},
// {'d': 	Ngày Quốc tế của Liên Hợp Quốc trong hỗ trợ nạn nhân của tra tấn'},
// {'d': 	Ngày Quốc tế Phòng chống Bạch tạng'},
// {'d': Thứ Bảy đầu tiên	Ngày Quốc tế Hợp tác'},
// {'d': 11/7	Ngày Dân số Thế giới'},
// {'d': 15/7	Ngày Kỹ năng thanh niên thế giới'},
// {'d': 18/7	Ngày Quốc tế Nelson Mandela'},
// {'d': 28/7	Ngày Viêm gan Thế giới'},
// {'d': 30/7	Ngày Hữu nghị Quốc tế'},
// {'d': 	Ngày Thế giới phòng, chống mua bán người'},
// {'d': 12/8	Ngày Quốc tế Thanh Thiếu niên'},
// {'d': 23/8	Ngày Quốc tế Tưởng niệm Buôn bán nô lệ và Xoá bỏ nó'},
// {'d': 29/8	Ngày Quốc tế chống Thử nghiệm Hạt nhân'},
// {'d': 30/8	Ngày Quốc tế các Nạn nhân mất tích cưỡng bức'},
// {'d': 5/9	Ngày Quốc tế Từ thiện'},
// {'d': 8/9	Ngày Quốc tế biết Chữ'},
// {'d': 10/9	Ngày Thế giới Phòng chống Tự sát'},
// {'d': 12/9	Ngày Liên Hợp Quốc về Hợp tác Nam-Nam'},
// {'d': 15/9	Ngày Quốc tế vì Dân chủ'},
// {'d': 16/9	Ngày Quốc tế Bảo vệ Tầng ôzôn'},
// {'d': 21/9	Ngày Quốc tế Hòa bình'},
// {'d': Tuần cuối tháng 9	Ngày Hàng hải Thế giới'},
// {'d': 26/9	Ngày Quốc tế Xóa bỏ Hoàn toàn Vũ khí hạt nhân'},
// {'d': 	Ngày Tránh thai Thế giới'},
// {'d': 27/9	Ngày Du lịch thế giới'},
// {'d': 1/10	Ngày Quốc tế Người cao tuổi'},
// {'d': 2/10	Ngày quốc tế bất bạo động'},
// {'d': 5/10	Ngày Nhà giáo thế giới'},
// {'d': Thứ Hai đầu tiên	Ngày Môi trường sống Thế giới'},
// {'d': 9/10	Ngày Bưu chính thế giới'},
// {'d': 11/10	Ngày Quốc tế Trẻ em gái'},
// {'d': 13/10	Ngày Quốc tế Giảm nhẹ Thiên tai'},
// {'d': 14/10	Ngày Tiêu chuẩn Thế giới'},
// {'d': 15/10	Ngày Quốc tế Phụ nữ nông thôn'},
// {'d': 16/10	Ngày Lương thực thế giới'},
// {'d': 17/10	Ngày Quốc tế Xóa nghèo'},
// {'d': 24/10	Ngày Liên Hợp Quốc'},
// {'d': 	Ngày Thông tin về Phát triển thế giới'},
// {'d': 27/10	Ngày Thế giới về Di sản Nghe nhìn'},
// {'d': 31/10	Ngày Thành phố Thế giới'},
// {'d': 2/11	Ngày Quốc tế về Chấm dứt Không bị trừng phạt cho Tội ác chống lại các nhà báo'},
// {'d': 6/11	Ngày Quốc tế Phòng chống khai thác Môi trường trong Chiến tranh và Xung đột vũ trang'},
// {'d': 10/11	Ngày Khoa học Thế giới vì Hòa bình và Phát triển'},
// {'d': 14/11	Ngày Thế giới phòng, chống đái tháo đường'},
// {'d': Chủ nhật thứ 3	Ngày Thế giới Tưởng niệm Nạn nhân Giao thông đường bộ'},
// {'d': 16/11	Ngày Khoan dung Quốc tế'},
// {'d': 19/11	Ngày Toilet Thế giới'},
// {'d': 	Ngày Quốc tế Nam giới'},
// {'d': Thứ Năm thứ 3	Ngày Triết học thế giới'},
// {'d': 20/11	Ngày Thiếu nhi Thế giới'},
// {'d': 21/11	Ngày Truyền hình thế giới'},
// {'d': 25/11	Ngày quốc tế loại bỏ bạo lực đối với Phụ nữ'},
// {'d': 29/11	Ngày Quốc tế Đoàn kết với Nhân dân Palestine'},
// {'d': 1/12	Ngày thế giới phòng chống bệnh AIDS'},
// {'d': 2/12	Ngày Quốc tế Giải phóng Nô lệ'},
// {'d': 3/12	Ngày Quốc tế Người khuyết tật'},
// {'d': 5/12	Ngày Tình nguyện Quốc tế vì Phát triển Kinh tế và Xã hội'},
// {'d': 	Ngày Đất Thế giới'},
// {'d': 7/12	Ngày Hàng không Dân dụng Quốc tế'},
// {'d': 9/12	Ngày Quốc tế chống Tham nhũng'},
// {'d': 10/12	Ngày Nhân quyền Quốc tế'},
// {'d': 11/12	Ngày Núi Quốc tế'},
// {'d': 15/12	Ngày Chè Quốc tế'},
// {'d': 18/12	Ngày Di dân Quốc tế'},
// {'d': 20/12	Ngày Đoàn kết Con người Quốc tế'},
// {'d': 25/12	Lễ Giáng Sinh'},
// {'d': 27/12	Ngày Quốc tế Phòng, chống dịch bệnh'},
];