const LUNAR_ANNIVERSARY_DAYS = [
  {'d': 1, 'm': 1,'i': 'Tết Nguyên Đán'},
  {'d': 15, 'm': 1,'i': 'Tết Nguyên Tiêu'},
  {'d': 3, 'm': 3,'i': 'Tết Hàn Thực'},
  {'d': 15, 'm': 4,'i': 'Lễ Phật Đản'},
  {'d': 5, 'm': 5,'i': 'Tết Đoan Ngọ'},
  {'d': 15, 'm': 7,'i': 'Lễ Vu Lan'},
  {'d': 15, 'm': 8,'i': 'Tết Trung Thu'},
  {'d': 23, 'm': 12,'i': 'Ngày Đưa Ông Táo Về Trời'}
];

const SOLAR_ANNIVERSARY_DAYS = [
  {'d': 9, 'm': 1,'i': 'Ngày Truyền Thống Học sinh, Sinh viên Việt Nam (1950)'},
  {'d': 3, 'm': 2,'i': 'Ngày thành lập Đảng Cộng sản Việt Nam (1930)'},
  {'d': 27, 'm': 2,'i': 'Ngày Thầy thuốc Việt Nam (1955)'},
  {'d': 1, 'm': 3,'i': 'Ngày sinh của Đồng chí Phạm Văn Đồng (1906)'},
  {'d': 3, 'm': 3,'i': 'Ngày Truyền Thống Bộ đội Biên phòng (1959)'},
  {'d': 8, 'm': 3,'i': 'Ngày Quốc tế Phụ nữ (1910)'},
  {'d': 20, 'm': 3,'i': 'Ngày Quốc tế Hạnh phúc'},
  {'d': 22, 'm': 3,'i': 'Ngày Nước sạch Thế giới'},
  {'d': 26, 'm': 3,'i': 'Ngày thành lập Đoàn Thanh niên Cộng sản Hồ Chí Minh (1931)'},
  {'d': 27, 'm': 3,'i': 'Ngày Thể thao Việt Nam (1991)'},
  {'d': 28, 'm': 3,'i': 'Ngày thành lập Lực Lượng Dân Quân Tự Vệ (1935)'},
  {'d': 21, 'm': 4,'i': 'Ngày sách Việt Nam (2014)'},
  {'d': 29, 'm': 4,'i': 'Ngày mất của Đồng chí Phạm Văn Đồng (2000)'},
  {'d': 30, 'm': 4,'i': 'Ngày Giải phóng Miền Nam, Thống nhất Đất nước (1975)'},
  {'d': 1, 'm': 5,'i': 'Quốc tế lao động (1886)'},
  {'d': 6, 'm': 5,'i': 'Ngày giỗ của Đồng chí Phạm Văn Đồng (2000)'},
  {'d': 7, 'm': 5,'i': 'Ngày chiến thắng Điện Biên Phủ (1954)'},
  {'d': 15, 'm': 5,'i': 'Ngày thành lập Đội Thiếu niên Tiền phong Hồ Chí Minh (1941)'},
  {'d': 19, 'm': 5,'i': 'Ngày sinh của Chủ tịch Hồ Chí Minh (1890)'},
  {'d': 1, 'm': 6,'i': 'Ngày Quốc tế Thiếu nhi'},
  {'d': 5, 'm': 6,'i': 'Ngày Bác Hồ ra đi tìm đường cứu nước (1911)'},
  {'d': 21, 'm': 6,'i': 'Ngày Báo chí Cách mạng Việt Nam (1925)'},
  {'d': 28, 'm': 6,'i': 'Ngày Gia đình Việt Nam (2001)'},
  {'d': 1, 'm': 7,'i': 'Ngày Bảo hiểm Y tế Việt Nam (2009)'},
  {'d': 15, 'm': 7,'i': 'Ngày Truyền thống Lực lượng Thanh niên xung phong Việt Nam (1950)'},
  {'d': 27, 'm': 7,'i': 'Ngày Thương binh Liệt sĩ (1947)'},
  {'d': 28, 'm': 7,'i': 'Ngày thành lập Công đoàn Việt Nam (1929)'},
  {'d': 19, 'm': 8,'i': 'Ngày Cách mạng tháng Tám thành công (1945)'},
  {'d': 2, 'm': 9,'i': 'Ngày Quốc khánh (1945)'},
  {'d': 7, 'm': 10,'i': 'Ngày thành lập Đài Tiếng nói Việt Nam (1945)'},
  {'d': 10, 'm': 9,'i': 'Ngày thành lập Mặt trận Tổ quốc Việt Nam (1955)'},
  {'d': 2, 'm': 10,'i': 'Ngày Khuyến học Việt Nam (1996)'},
  {'d': 10, 'm': 10,'i': 'Ngày giải phóng thủ đô (1954)'},
  {'d': 14, 'm': 10,'i': 'Ngày thành lập Hội Nông dân Việt Nam (1930)'},
  {'d': 15, 'm': 10,'i': 'Ngày truyền thống Hội Liên hiệp Thanh niên Việt Nam (1956)'},
  {'d': 20, 'm': 10,'i': 'Ngày Phụ nữ Việt Nam (1930)'},
  {'d': 9, 'm': 11,'i': 'Ngày Pháp luật Việt Nam (1946)'},
  {'d': 18, 'm': 11,'i': 'Ngày Thành lập Mặt trận Dân tộc Thống nhất Việt Nam (1930)'},
  {'d': 19, 'm': 11,'i': 'Ngày Quốc Tế Nam Giới'},
  {'d': 20, 'm': 11,'i': 'Ngày Nhà giáo Việt Nam (1982)'},
  {'d': 6, 'm': 12,'i': 'Ngày Thành lập Hội Cựu Chiến binh Việt Nam (1989)'},
  {'d': 20, 'm': 12,'i': 'Ngày Thành lập Mặt trận Dân tộc Giải phóng miền Nam Việt Nam (1960)'},
  {'d': 24, 'm': 12,'i': 'Lễ Giáng Sinh'},
  {'d': 22, 'm': 12,'i': 'Ngày thành lập Quân đội Nhân dân Việt Nam (1944)'},
];